# fly.toml app configuration file generated for my-langgraph-app on 2025-09-24T15:18:33-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-langgraph-app'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8123
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
